-- migrate:up
CREATE TABLE holidays (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  holiday_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE holidays;
